### ISSUE TITLE
Cannot read property 'select2' of undefined

### ISSUE THREAD

**Issue by dragma** [rkit/react-select2-wrapper#6]
Hi,
I've got this error when I load the module 
`import Select2 from 'react-select2-wrapper';`

I'm using Babel, Webpack and React on a 4.2.2 nodejs.

**Comment by rkit** [comment]
Do you use last version?
Can you show the webpack config?

**Comment by dragma** [comment]
Hi, 
I use the current version "0.0.9" available on NPM.
https://www.npmjs.com/package/react-select2-wrapper

Here is my `webpack.config.babel.js` config file
```
import path from 'path';
import webpack from 'webpack';

import ExtractTextPlugin from "extract-text-webpack-plugin";


const config = {
    entry: [
        './src/client/client.js',
        './src/scss/main.scss'
    ],

    resolve: {
        extensions: ['', '.js', '.jsx', '.scss', '.jpg', '.png']
    },

    output: {
        path: path.join(__dirname, 'statics/build'),
        filename: 'myfile.js',
        publicPath: '/statics/'
    },

    module: {
        loaders: [
            {
                test: /\.js$|\.jsx$/,
                loader: 'babel',
                exclude: /node_modules/
            },
            {
                test:  /\.(eot|woff|woff2|ttf|svg)$/,
                loader: 'file-loader?name=statics/build/[name].[ext]',
                exclude: /node_modules/
            },
            {
                test:  /\.(jpe?g|png|gif)$/,
                loader: 'file-loader?name=statics/img/[name].[ext]',
                exclude: /node_modules/
            },
            {
                test: /\.scss$/,
                exclude: /node_modules/,
                loader: ExtractTextPlugin.extract("style-loader", "css!sass")
            }
        ]
    },
    plugins: [
        new ExtractTextPlugin("myfile.css")
    ]
};

export default config;
```

Thanks for you reply. =)

Merry christmas !

D.

**Comment by rkit** [comment]
> Thanks for you reply. =)
Thanks, and you )

A very strange error. I can't reproduce the error.
I would like more information…

> I've got this error when I load the module 
> import Select2 from 'react-select2-wrapper';

Can you tell which line in your code is causing the error?

**Comment by dragma** [comment]
Here is my stacktrace :
```
server-0 TypeError: Cannot read property 'select2' of undefined
server-0     at /home/florent/***/node_modules/react-select2-wrapper/node_modules/select2/dist/js/select2.js:5500:11
server-0     at main (/home/florent/***/node_modules/react-select2-wrapper/node_modules/select2/dist/js/select2.js:345:39)
server-0     at callDep (/home/florent/***/node_modules/react-select2-wrapper/node_modules/select2/dist/js/select2.js:211:18)
server-0     at Object.req [as require] (/home/florent/***/node_modules/react-select2-wrapper/node_modules/select2/dist/js/select2.js:376:20)
server-0     at /home/florent/***/node_modules/react-select2-wrapper/node_modules/select2/dist/js/select2.js:5561:20
server-0     at S2 (/home/florent/***/node_modules/react-select2-wrapper/node_modules/select2/dist/js/select2.js:14:5)
server-0     at Object.<anonymous> (/home/florent/***/node_modules/react-select2-wrapper/node_modules/select2/dist/js/select2.js:19:2)
server-0     at Module._compile (module.js:435:26)
server-0     at Module._extensions..js (module.js:442:10)
server-0     at Object.require.extensions.(anonymous function) [as .js] (/home/florent/***/node_modules/babel-core/node_modules/babel-register/lib/node.js:135:7)
```
Iim running my application on an 14.04 Ubuntu, wint nvm, pm2, babel and webpack (for the moment).
Ask me anything else you want.

Have a great day !

**Comment by webholics** [comment]
This happens in universal JS applications where you run the same code in a node environment for server side rendering. Unfortunately the problem lies in select2 itself, see https://github.com/select2/select2/issues/3282

**Comment by dragma** [comment]
Thank you !
I'll keep an eye on it. :)

**Comment by rkit** [comment]
I closed. Let me know if you need something…
