### ISSUE TITLE
TypeError: this.el.select2 is not a function

### ISSUE THREAD

**Issue by scottybollinger** [rkit/react-select2-wrapper#83]
https://github.com/rkit/react-select2-wrapper/issues/36 is still happening with the latest version `1.0.4-beta`. 

`TypeError: this.el.select2 is not a function` when mounting a component in a Jest unit test.

**Comment by Dcuevac93** [comment]
I'm having the same problem. This is what i have in my `package.json` `"react-select2-wrapper": "^1.0.4-beta5"`. Any solution?

**Comment by CWSites** [comment]
I'm also having the same issue with the latest `1.0.4-beta6`

```
TypeError: this.el.select2 is not a function
        at Select2.initSelect2 (node_modules/react-select2-wrapper/lib/components/Select2.js:94:15)
        at Select2.componentDidMount (node_modules/react-select2-wrapper/lib/components/Select2.js:64:12)
```

**Comment by agungyuliaji** [comment]
i only got this error when using `jest + enzyme`

**Comment by CWSites** [comment]
@rkit any help you could provide here? I've spent a week trying to figure this out, building mocks for select2, importing jquery in different places, etc. This is the only issue preventing me from using your library.

**Comment by agungyuliaji** [comment]
solved by adding this

```
global.$ = require('jquery')
global.$.fn.select2 = require('select2')
```

on jest setup file

**Comment by CWSites** [comment]
Thank you @agungyuliaji, you're a lifesaver!

**Comment by agungyuliaji** [comment]
Glad to hear that!
anyway it's jest problem. the issue is not related with this plugin.

**Comment by syedn** [comment]
the issue was resolved for me when I added 
global.$ = require('jquery')
global.$.fn.select2 = require('select2')
to app.js 

Thanks @agungyuliaji

**Comment by CWSites** [comment]
@rkit this can be closed.
